// <auto-generated />
namespace Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class dfgdfgfg43435454 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfgdfgfg43435454));
        
        string IMigrationMetadata.Id
        {
            get { return "201502091359599_dfgdfgfg43435454"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
